apiVersion: v1
kind: Service
metadata:
  name: goweb-helloworld-svc
  namespace: goweb-helloworld
spec:
  selector:
    app: goweb-helloworld-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer