name: Release Container Image to Docker Hub

on:
  push:
    tags:
      - "*.*.*"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Pring github ref
      run: echo ${{ github.ref }}

    - name: Pring tag
      run: echo ${{ github.event.release.tag_name }}